apiVersion: v2
appVersion: 1.7.0
description: Qwen3-Reranker-0.6B via vllm on NVIDIA RTX 5090 (Blackwell)
home: https://github.com/bayerhazard/aimighty-reranker
keywords:
- ai
- reranker
- vllm
- rag
- nvidia
- blackwell
maintainers:
- email: admin@aimighty.local
  name: Aimighty
name: aimrerqwen3vllm
sources:
- https://github.com/bayerhazard/aimighty-reranker
type: application
version: 1.9.0
